pipeline:
  name: aiAgentCIIntelligence
  identifier: aiAgentCIIntelligence
  projectIdentifier: Labs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.adminGithub
        repoName: AiAgentTester
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8testcluster
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Windows
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockervanshajb10
                    image: alpine:latest
                    shell: Sh
                    command: echo "hey man!"
              - stepGroup:
                  name: "Actual AI Agent - CI Intelligence "
                  identifier: Actual_AI_Agent_CI_Intelligence
                  steps:
                    - step:
                        type: Agent
                        name: CI Intel Agent
                        identifier: CI_Intel_Agent
                        spec:
                          agentName: buildTurbo
                          agentSettings:
                            model_name: global.anthropic.claude-opus-4-6-v1
                            test_agent_llm_connector: ""
                            cache_intel_use_custom_key: false
                            llm_connector: account.harnessAnthropic
                            mcp_connectors:
                              - account.mcpConnector001
